name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  smoke-test:
    name: Smoke Tests
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Run software installer
      run: ./src/installer/install.sh
    
    - name: Run software upgrade
      run: ./src/installer/upgrade.sh
    
    - name: Run dotfiles installer
      run: ./src/dotfiles/install.sh
